"""
core/xbrl_extractor.py
Extract financial metrics from XBRL HTML files.
Supports selective extraction via selected_metrics parameter.
"""
from pathlib import Path
from bs4 import BeautifulSoup
import pandas as pd

# ═══════════════════════════════════════════════════════
# KATALOG LENGKAP — dikelompokkan per kategori
# ═══════════════════════════════════════════════════════
METRICS_CATALOG = {
    "Informasi Umum": [
        'Nama entitas',
        'Penjelasan perubahan nama dari akhir periode laporan sebelumnya',
        'Kode entitas',
        'Nomor identifikasi entitas',
        'Industri utama entitas',
        'Standar akuntansi yang dipilih',
        'Sektor',
        'Subsektor',
        'Industri',
        'Subindustri',
        'Informasi pemegang saham pengendali',
        'Jenis entitas',
        'Jenis efek yang dicatatkan',
        'Jenis papan perdagangan tempat entitas tercatat',
        'Apakah merupakan laporan keuangan satu entitas atau suatu kelompok entitas',
        'Periode penyampaian laporan keuangan',
        'Tanggal Surat Pernyataan Direksi',
        'Tanggal awal periode berjalan',
        'Tanggal akhir periode berjalan',
        'Tanggal akhir tahun sebelumnya',
        'Tanggal awal periode sebelumnya',
        'Tanggal akhir periode sebelumnya',
        'Tanggal akhir 2 tahun sebelumnya',
        'Mata uang pelaporan',
        'Kurs konversi pada tanggal pelaporan jika mata uang penyajian selain rupiah',
        'Pembulatan yang digunakan dalam penyajian jumlah dalam laporan keuangan',
        'Jenis laporan atas laporan keuangan',
        'Jenis opini auditor',
        'Hal yang diungkapkan dalam paragraf pendapat untuk penekanan atas suatu masalah atau paragraf penjelasan lainnya, jika ada',
        'Hasil penugasan review',
        'Opini Hal Audit Utama',
        'Jumlah Hal Audit Utama',
        'Paragraf Hal Audit Utama',
        'Tanggal laporan audit atau hasil laporan review',
        'Auditor tahun berjalan',
        'Nama partner audit tahun berjalan',
        'Lama tahun penugasan partner yang menandatangani',
        'Auditor tahun sebelumnya',
        'Nama partner audit tahun sebelumnya',
        'Kepatuhan terhadap pemenuhan peraturan OJK Nomor: 75/POJK.04/2017 tentang Tanggung Jawab Direksi Atas Laporan Keuangan',
        'Kepatuhan terhadap pemenuhan independensi akuntan yang memberikan jasa audit di pasar modal sesuai dengan POJK Nomor 13/POJK.03/2017 tentang Penggunaan Jasa Akuntan Publik dalam Kegiatan Jasa Keuangan',
    ],
    "Neraca (Balance Sheet)": [
        'Kas dan setara kas',
        'Wesel tagih',
        'Investasi jangka pendek',
        'Dana yang dibatasi penggunaannya lancar',
        'Aset keuangan lancar yang diukur pada nilai wajar melalui laba rugi',
        'Aset keuangan lancar nilai wajar melalui pendapatan komprehensif lainnya',
        'Aset keuangan biaya perolehan diamortisasi lancar',
        'Aset keuangan lancar lainnya',
        'Aset keuangan derivatif lancar',
        'Piutang usaha pihak ketiga',
        'Piutang usaha pihak berelasi',
        'Piutang sewa pembiayaan lancar',
        'Piutang retensi pihak ketiga',
        'Piutang retensi pihak berelasi',
        'Tagihan bruto pemberi kerja pihak ketiga',
        'Tagihan bruto pemberi kerja pihak berelasi',
        'Piutang subsidi',
        'Piutang nasabah lancar pihak ketiga',
        'Piutang nasabah lancar pihak berelasi',
        'Piutang margin',
        'Piutang dari lembaga kliring dan penjaminan',
        'Piutang premi dan reasuransi',
        'Piutang dividen dan bunga',
        'Piutang lainnya pihak ketiga',
        'Piutang lainnya pihak berelasi',
        'Persediaan lancar',
        'Persediaan hewan ternak lancar',
        'Aset real estat lancar',
        'Aset biologis lancar',
        'Biaya dibayar dimuka lancar',
        'Jaminan lancar',
        'Uang muka lancar atas investasi',
        'Uang muka lancar atas pembelian aset tetap',
        'Uang muka lancar lainnya',
        'Pajak dibayar dimuka lancar',
        'Klaim atas pengembalian pajak lancar',
        'Biaya pengupasan tanah yang ditangguhkan lancar',
        'Biaya mobilisasi yang ditangguhkan lancar',
        'Aset pengampunan pajak lancar',
        'Aset non-keuangan lancar lainnya',
        'Aset tidak lancar atau kelompok lepasan diklasifikasikan sebagai dimiliki untuk dijual',
        'Aset tidak lancar atau kelompok lepasan diklasifikasikan sebagai dimiliki untuk didistribusikan kepada pemilik',
        'Piutang sewa pembiayaan tidak lancar',
        'Dana yang dibatasi penggunaannya tidak lancar',
        'Dana cadangan perawatan pesawat',
        'Piutang dari pihak berelasi',
        'Piutang dari pemegang saham',
        'Piutang nasabah tidak lancar pihak ketiga',
        'Piutang nasabah tidak lancar pihak berelasi',
        'Piutang tidak lancar lainnya pihak ketiga',
        'Piutang tidak lancar lainnya pihak berelasi',
        'Investasi pada entitas ventura bersama',
        'Investasi pada entitas asosiasi',
        'Jaminan tidak lancar',
        'Uang muka tidak lancar atas investasi',
        'Uang muka tidak lancar atas pembelian aset tetap',
        'Uang muka tidak lancar lainnya',
        'Aset keuangan tidak lancar yang diukur pada nilai wajar melalui laba rugi',
        'Aset keuangan tidak lancar nilai wajar melalui pendapatan komprehensif lainnya',
        'Aset keuangan tidak lancar biaya perolehan diamortisasi',
        'Aset keuangan tidak lancar lainnya',
        'Aset keuangan derivatif tidak lancar',
        'Biaya dibayar dimuka tidak lancar',
        'Pajak dibayar dimuka tidak lancar',
        'Aset pajak tangguhan',
        'Persediaan tidak lancar',
        'Persediaan hewan ternak tidak lancar',
        'Aset real estat tidak lancar',
        'Persediaan tidak lancar lainnya',
        'Hewan ternak produksi',
        'Hutan tanaman industri menghasilkan',
        'Hutan tanaman industri belum menghasilkan',
        'Tanaman perkebunan menghasilkan',
        'Tanaman perkebunan belum menghasilkan',
        'Aset biologis tidak lancar',
        'Perkebunan plasma',
        'Aset reasuransi',
        'Properti investasi',
        'Tanah Belum Dikembangkan',
        'Aset tetap',
        'Aset hak guna',
        'Aset ijarah',
        'Agunan yang diambil alih',
        'Aset minyak dan gas bumi',
        'Aset eksplorasi dan evaluasi',
        'Hak konsesi jalan tol',
        'Properti pertambangan',
        'Biaya pengupasan tanah yang ditangguhkan tidak lancar',
        'Biaya mobilisasi yang ditangguhkan tidak lancar',
        'Beban tangguhan hak atas tanah dan bangunan',
        'Beban tangguhan atas biaya eksplorasi dan pengembangan',
        'Beban tangguhan atas biaya pengelolaan hak pengusahaan hutan',
        'Beban tangguhan atas biaya pengelolaan dan reklamasi lingkungan hidup',
        'Beban tangguhan lainnya',
        'Klaim atas pengembalian pajak tidak lancar',
        'Aset imbalan pasca kerja',
        'Goodwill',
        'Aset takberwujud selain goodwill',
        'Aset pengampunan pajak tidak lancar',
        'Aset tidak lancar non-keuangan lainnya',
        'Kas',
        'Dana yang dibatasi penggunaannya',
        'Giro pada Bank Indonesia',
        'Giro pada bank lain pihak ketiga',
        'Giro pada bank lain pihak berelasi',
        'Cadangan kerugian penurunan nilai pada giro pada bank lain',
        'Penempatan pada Bank Indonesia dan bank lain pihak ketiga',
        'Penempatan pada Bank Indonesia dan bank lain pihak berelasi',
        'Cadangan kerugian penurunan nilai pada penempatan pada bank lain',
        'Piutang asuransi pihak ketiga',
        'Piutang asuransi pihak berelasi',
        'Cadangan kerugian penurunan nilai pada piutang asuransi',
        'Biaya akuisisi tangguhan',
        'Deposito pada lembaga kliring dan penjaminan',
        'Efek-efek yang diperdagangkan pihak ketiga',
        'Efek-efek yang diperdagangkan pihak berelasi',
        'Cadangan kerugian penurunan nilai pada efek-efek yang diperdagangkan',
        'Investasi pemegang polis pada kontrak unit-linked',
        'Efek yang dibeli dengan janji dijual kembali',
        'Wesel ekspor dan tagihan lainnya pihak ketiga',
        'Wesel ekspor dan tagihan lainnya pihak berelasi',
        'Cadangan kerugian penurunan nilai pada wesel ekspor dan tagihan lainnya',
        'Tagihan akseptasi pihak ketiga',
        'Tagihan akseptasi pihak berelasi',
        'Cadangan kerugian penurunan nilai pada tagihan akseptasi',
        'Tagihan derivatif pihak ketiga',
        'Tagihan derivatif pihak berelasi',
        'Pinjaman yang diberikan pihak ketiga',
        'Pinjaman yang diberikan pihak berelasi',
        'Cadangan kerugian penurunan nilai pada pinjaman yang diberikan',
        'Piutang murabahah pihak ketiga',
        'Piutang murabahah pihak berelasi',
        'Cadangan kerugian penurunan nilai pada piutang murabahah',
        'Piutang istishna pihak ketiga',
        'Piutang istishna pihak berelasi',
        'Cadangan kerugian penurunan nilai pada piutang istishna',
        'Piutang ijarah pihak ketiga',
        'Piutang ijarah pihak berelasi',
        'Cadangan kerugian penurunan nilai pada piutang ijarah',
        'Piutang pembiayaan konsumen pihak ketiga',
        'Piutang pembiayaan konsumen pihak berelasi',
        'Cadangan kerugian penurunan nilai pada piutang pembiayaan konsumen',
        'Pinjaman qardh pihak ketiga',
        'Pinjaman qardh pihak berelasi',
        'Cadangan kerugian penurunan nilai pada pinjaman qardh',
        'Pembiayaan mudharabah pihak ketiga',
        'Pembiayaan mudharabah pihak berelasi',
        'Cadangan kerugian penurunan nilai pada pembiayaan mudharabah',
        'Pembiayaan musyarakah pihak ketiga',
        'Pembiayaan musyarakah pihak berelasi',
        'Cadangan kerugian penurunan nilai pada pembiayaan musyarakah',
        'Investasi sewa pihak ketiga',
        'Investasi sewa pihak berelasi',
        'Investasi sewa nilai residu yang terjamin',
        'Investasi sewa pendapatan pembiayaan tangguhan',
        'Investasi sewa simpanan jaminan',
        'Cadangan kerugian penurunan nilai pada investasi sewa',
        'Tagihan anjak piutang pihak ketiga',
        'Tagihan anjak piutang pihak berelasi',
        'Tagihan anjak piutang pada pendapatan anjak piutang tangguhan',
        'Cadangan kerugian penurunan nilai pada tagihan anjak piutang',
        'Piutang lainnya pihak ketiga',
        'Piutang lainnya pihak berelasi',
        'Cadangan kerugian penurunan nilai pada piutang lainnya',
        'Aset keuangan lainnya',
        'Obligasi pemerintah',
        'Uang muka',
        'Biaya dibayar dimuka',
        'Jaminan',
        'Pajak dibayar dimuka',
        'Klaim atas pengembalian pajak',
        'Aset lainnya',
        'Utang bank jangka pendek',
        'Utang trust receipts',
        'Pinjaman jangka pendek non-bank',
        'Utang usaha pihak ketiga',
        'Utang usaha pihak berelasi',
        'Utang lainnya pihak ketiga',
        'Utang lainnya pihak berelasi',
        'Uang muka pelanggan jangka pendek pihak ketiga',
        'Uang muka pelanggan jangka pendek pihak berelasi',
        'Utang dividen',
        'Liabilitas keuangan jangka pendek lainnya',
        'Beban akrual jangka pendek',
        'Liabilitas imbalan pasca kerja jangka pendek',
        'Utang pajak',
        'Utang cukai',
        'Utang proyek',
        'Utang kepada lembaga kliring dan penjaminan',
        'Utang nasabah pihak ketiga',
        'Utang nasabah pihak berelasi',
        'Utang koasuransi',
        'Utang reasuransi',
        'Liabilitas anjak piutang',
        'Uang jaminan jangka pendek',
        'Pendapatan diterima dimuka jangka pendek',
        'Liabilitas bruto kepada pemberi kerja pihak ketiga',
        'Liabilitas bruto kepada pemberi kerja pihak berelasi',
        'Pendapatan ditangguhkan jangka pendek',
        'Provisi jangka pendek pelapisan jalan tol',
        'Provisi jangka pendek biaya pengembalian dan pemeliharaan pesawat',
        'Provisi jangka pendek pembangunan prasarana, fasilitas umum, dan sosial',
        'Provisi jangka pendek biaya pembongkaran aset tetap',
        'Provisi jangka pendek restorasi dan rehabilitasi',
        'Provisi jangka pendek lainnya',
        'Liabilitas pembayaran berbasis saham',
        'Kontrak liabilitas jangka pendek',
        'Liabilitas yang secara langsung berhubungan dengan aset tidak lancar atau kelompok lepasan yang diklasifikasikan sebagai dimiliki untuk dijual',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang bank',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang keuangan keuangan non bank',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman beragunan',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman tanpa agunan',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas penerusan pinjaman',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman dari pemerintah republik Indonesia',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman subordinasi',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas liabilitas kerja sama operasi',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas liabilitas pembebasan tanah',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang pembiayaan konsumen',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas liabilitas sewa pembiayaan',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang listrik swasta',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang retensi',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas wesel bayar',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas surat utang jangka menengah',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang obligasi',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas sukuk',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas obligasi subordinasi',
        'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman lainnya',
        'Utang pihak berelasi jangka pendek',
        'Utang pemegang saham jangka pendek',
        'Liabilitas keuangan derivatif jangka pendek',
        'Liabilitas pengampunan pajak lancar',
        'Liabilitas non-keuangan jangka pendek lainnya',
        'Liabilitas keuangan derivatif jangka panjang',
        'Liabilitas pajak tangguhan',
        'Utang pihak berelasi jangka panjang',
        'Utang pemegang saham jangka panjang',
        'Kontrak liabilitas jangka panjang',
        'Liabilitas jangka panjang atas utang bank',
        'Utang lembaga keuangan non-bank',
        'Liabilitas jangka panjang atas penerusan pinjaman',
        'Liabilitas jangka panjang atas pinjaman beragunan',
        'Liabilitas jangka panjang atas pinjaman tanpa agunan',
        'Liabilitas jangka panjang atas pinjaman dari pemerintah republik Indonesia',
        'Liabilitas jangka panjang atas pinjaman subordinasi',
        'Liabilitas jangka panjang atas liabilitas kerja sama operasi',
        'Liabilitas jangka panjang atas liabilitas pembebasan tanah',
        'Liabilitas jangka panjang atas utang pembiayaan konsumen',
        'Liabilitas jangka panjang atas liabilitas sewa pembiayaan',
        'Liabilitas jangka panjang atas utang listrik swasta',
        'Liabilitas jangka panjang atas utang retensi',
        'Liabilitas jangka panjang atas wesel bayar',
        'Liabilitas jangka panjang atas surat utang jangka menengah',
        'Liabilitas jangka panjang atas utang obligasi',
        'Liabilitas jangka panjang atas sukuk',
        'Liabilitas jangka panjang atas obligasi subordinasi',
        'Liabilitas jangka panjang atas pinjaman lainnya',
        'Obligasi konversi',
        'Pendapatan diterima dimuka jangka panjang',
        'Uang jaminan jangka panjang',
        'Uang muka pelanggan jangka panjang pihak ketiga',
        'Uang muka pelanggan jangka panjang pihak berelasi',
        'Pendapatan ditangguhkan jangka panjang',
        'Liabilitas kontrak asuransi',
        'Provisi pelapisan jalan tol jangka panjang',
        'Provisi biaya pengembalian dan pemeliharaan pesawat jangka panjang',
        'Provisi pembangunan prasarana, fasilitas umum, dan sosial jangka panjang',
        'Provisi biaya pembongkaran aset tetap jangka panjang',
        'Provisi restorasi dan rehabilitasi jangka panjang',
        'Provisi jangka panjang lainnya',
        'Biaya pengupasan tanah yang masih harus dibayar',
        'Liabilitas kepada pemegang polis',
        'Kewajiban imbalan pasca kerja jangka panjang',
        'Liabilitas pengampunan pajak tidak lancar',
        'Liabilitas keuangan jangka panjang lainnya',
        'Liabilitas non-keuangan jangka panjang',
        'Liabilitas segera',
        'Bagi hasil yang belum dibagikan',
        'Dana simpanan syariah',
        'Giro pihak ketiga',
        'Giro pihak berelasi',
        'Giro wadiah pihak ketiga',
        'Giro wadiah pihak berelasi',
        'Tabungan pihak ketiga',
        'Tabungan pihak berelasi',
        'Tabungan wadiah pihak ketiga',
        'Tabungan wadiah pihak berelasi',
        'Deposito berjangka pihak ketiga',
        'Deposito berjangka pihak berelasi',
        'Deposito wakalah pihak ketiga',
        'Deposito wakalah pihak berelasi',
        'Simpanan dari bank lain pihak berelasi',
        'Simpanan dari bank lain pihak ketiga',
        'Efek yang dijual dengan janji untuk dibeli kembali',
        'Liabilitas derivatif pihak ketiga',
        'Liabilitas derivatif pihak berelasi',
        'Utang asuransi',
        'Liabilitas kepada pemegang polis unit-linked',
        'Utang bunga',
        'Liabilitas akseptasi pihak berelasi',
        'Liabilitas akseptasi pihak ketiga',
        'Uang muka dan angsuran',
        'Utang dealer',
        'Pinjaman yang diterima pihak ketiga',
        'Pinjaman yang diterima pihak berelasi',
        'Pinjaman yang diterima utang pada lembaga kliring dan penjaminan',
        'Utang obligasi',
        'Sukuk',
        'Obligasi subordinasi',
        'Surat utang jangka menengah',
        'Efek yang diterbitkan lainnya',
        'Utang perusahaan efek',
        'Liabilitas atas kontrak',
        'Pendapatan ditangguhkan',
        'Liabilitas sewa pembiayaan',
        'Estimasi kerugian komitmen dan kontinjensi',
        'Beban akrual',
        'Liabilitas pengampunan pajak',
        'Liabilitas lainnya',
        'Kewajiban imbalan pasca kerja',
        'Pinjaman subordinasi pihak ketiga',
        'Pinjaman subordinasi pihak berelasi',
        'Giro mudharabah pihak ketiga',
        'Giro berjangka mudharabah pihak berelasi',
        'Tabungan mudharabah pihak ketiga',
        'Tabungan mudharabah pihak berelasi',
        'Deposito berjangka mudharabah pihak ketiga',
        'Deposito berjangka mudharabah pihak berelasi',
        'Tabungan mudharabah (ummat)',
        'Efek yang diterbitkan bank',
        'Investasi mudharabah antar bank',
        'Sukuk mudharabah',
        'Sukuk mudharabah subordinasi',
        'Jumlah akumulasi dana tabarru',
        'Saham biasa',
        'Saham preferen',
        'Tambahan modal disetor',
        'Saham treasuri',
        'Uang muka setoran modal',
        'Opsi saham',
        'Cadangan revaluasi',
        'Cadangan selisih kurs penjabaran',
        'Cadangan perubahan nilai wajar aset keuangan nilai wajar melalui pendapatan komprehensif lainnya',
        'Cadangan keuntungan (kerugian) investasi pada instrumen ekuitas',
        'Cadangan pembayaran berbasis saham',
        'Cadangan lindung nilai arus kas',
        'Cadangan pengukuran kembali program imbalan pasti',
        'Cadangan lainnya',
        'Selisih Transaksi Perubahan Ekuitas Entitas Anak/Asosiasi',
        'Komponen ekuitas lainnya',
        'Saldo laba yang telah ditentukan penggunaannya',
        'Saldo laba yang belum ditentukan penggunaannya',
        'Proforma ekuitas',
        'Kepentingan non-pengendali',
        'Cadangan umum dan wajib',
        'Cadangan khusus',
    ],
    "Laba Rugi (Income Statement)": [
        'Penjualan dan pendapatan usaha',
        'Beban pokok penjualan dan pendapatan',
        'Beban penjualan',
        'Beban umum dan administrasi',
        'Pendapatan dividen',
        'Pendapatan bunga',
        'Pendapatan investasi',
        'Pendapatan keuangan',
        'Beban bunga dan keuangan',
        'Keuntungan (kerugian) selisih kurs mata uang asing',
        'Bagian atas laba (rugi) entitas asosiasi yang dicatat dengan menggunakan metode ekuitas',
        'Bagian atas laba (rugi) entitas ventura bersama yang dicatat menggunakan metode ekuitas',
        'Keuntungan (kerugian) perubahan nilai wajar efek',
        'Keuntungan (kerugian) dari transaksi perdagangan efek yang telah direalisasi',
        'Keuntungan (kerugian) atas instrumen keuangan derivatif',
        'Beban pajak final',
        'Pendapatan lainnya',
        'Beban lainnya',
        'Keuntungan (kerugian) lainnya',
        'Pendapatan (beban) pajak',
        'Laba (rugi) dari operasi yang dihentikan',
        'Beban bunga',
        'Pendapatan pengelolaan dana oleh bank sebagai mudharib',
        'Hak pihak ketiga atas bagi hasil dana syirkah temporer',
        'Pendapatan dari premi asuransi',
        'Premi reasuransi',
        'Premi retrosesi',
        'Penurunan (kenaikan) premi yang belum merupakan pendapatan',
        'Penurunan (kenaikan) pendapatan premi disesikan kepada reasuradur',
        'Pendapatan komisi asuransi',
        'Pendapatan bersih investasi',
        'Penerimaan ujrah',
        'Pendapatan asuransi lainnya',
        'Beban klaim',
        'Klaim reasuransi',
        'Klaim retrosesi',
        'Kenaikan (penurunan) estimasi liabilitas klaim',
        'Kenaikan (penurunan) liabilitas manfaat polis masa depan',
        'Kenaikan (penurunan) provisi yang timbul dari tes kecukupan liabilitas',
        'Kenaikan (penurunan) liabilitas asuransi yang disesikan kepada reasuradur',
        'Kenaikan (penurunan) liabilitas pemegang polis pada kontrak unit-linked',
        'Beban komisi asuransi',
        'Ujrah dibayar',
        'Beban akuisisi dari kontrak asuransi',
        'Beban asuransi lainnya',
        'Pendapatan dari pembiayaan konsumen',
        'Pendapatan dari sewa pembiayaan',
        'Pendapatan dari sewa operasi',
        'Pendapatan dari anjak piutang',
        'Pendapatan sekuritas',
        'Pendapatan kegiatan penjamin emisi dan penjualan efek',
        'Pendapatan pembiayaan transaksi nasabah',
        'Pendapatan jasa biro administrasi efek',
        'Pendapatan kegiatan jasa manajer investasi',
        'Pendapatan kegiatan jasa penasehat keuangan',
        'Pendapatan provisi dan komisi dari transaksi lainnya selain kredit',
        'Pendapatan transaksi perdagangan',
        'Keuntungan (kerugian) yang telah direalisasi atas instrumen derivatif',
        'Penerimaan kembali aset yang telah dihapusbukukan',
        'Keuntungan (kerugian) pelepasan aset tetap',
        'Keuntungan (kerugian) pelepasan agunan yang diambil alih',
        'Pemulihan penyisihan kerugian penurunan nilai aset keuangan',
        'Pemulihan penyisihan kerugian penurunan nilai aset keuangan - sewa pembiayaan',
        'Pemulihan penyisihan kerugian penurunan nilai aset keuangan - piutang pembiayaan konsumen',
        'Pemulihan penyisihan kerugian penurunan nilai aset non-keuangan - agunan yang diambil alih',
        'Pemulihan penyisihan estimasi kerugian atas komitmen dan kontinjensi',
        'Pembentukan penyisihan kerugian penurunan nilai aset produktif',
        'Pembentukan penyisihan kerugian penurunan nilai aset non-produktif',
        'Pembalikan (beban) estimasi kerugian komitmen dan kontijensi',
        'Beban sewa, pemeliharaan, dan perbaikan',
        'Beban provisi dan komisi',
        'Pendapatan bukan operasional',
        'Beban bukan operasional',
        'Pendapatan komprehensif lainnya atas keuntungan (kerugian) hasil revaluasi aset tetap, sebelum pajak',
        'Pendapatan komprehensif lainnya atas pengukuran kembali kewajiban manfaat pasti, sebelum pajak',
        'Penyesuaian lainnya atas pendapatan komprehensif lainnya yang tidak akan direklasifikasi ke laba rugi, sebelum pajak',
        'Keuntungan (kerugian) selisih kurs penjabaran, sebelum pajak',
        'Penyesuaian reklasifikasi selisih kurs penjabaran, sebelum pajak',
        'Keuntungan (kerugian) yang belum direalisasi atas perubahan nilai wajar aset keuangan melalui penghasilan komprehensif lain, sebelum pajak',
        'Penyesuaian reklasifikasi atas aset keuangan nilai wajar melalui pendapatan komprehensif lainnya, sebelum pajak',
        'Keuntungan (kerugian) lindung nilai arus kas, sebelum pajak',
        'Penyesuaian reklasifikasi atas lindung nilai arus kas, sebelum pajak',
        'Nilai tercatat dari aset (liabilitas) non-keuangan yang perolehan atau keterjadiannya merupakan suatu prakiraan transaksi yang kemungkinan besar terjadi yang dilindung nilai, sebelum pajak',
        'Keuntungan (kerugian) lindung nilai investasi bersih kegiatan usaha luar negeri, sebelum pajak',
        'Penyesuaian reklasifikasi atas lindung nilai investasi bersih kegiatan usaha luar negeri, sebelum pajak',
        'Bagian pendapatan komprehensif lainnya dari entitas asosiasi yang dicatat dengan menggunakan metode ekuitas, sebelum pajak',
        'Bagian pendapatan komprehensif lainnya dari entitas ventura bersama yang dicatat dengan menggunakan metode ekuitas, sebelum pajak',
        'Penyesuaian lainnya atas pendapatan komprehensif lainnya yang akan direklasifikasi ke laba rugi, sebelum pajak',
        'Pajak atas pendapatan komprehensif lainnya',
        'Laba (rugi) yang dapat diatribusikan ke entitas induk',
        'Laba (rugi) yang dapat diatribusikan ke kepentingan non-pengendali',
        'Laba rugi komprehensif yang dapat diatribusikan ke entitas induk',
        'Laba rugi komprehensif yang dapat diatribusikan ke kepentingan non-pengendali',
        'Laba per saham dasar diatribusikan kepada pemilik entitas induk',
        'Laba (rugi) per saham dasar dari operasi yang dilanjutkan',
        'Laba (rugi) per saham dasar dari operasi yang dihentikan',
        'Laba (rugi) per saham dilusian dari operasi yang dilanjutkan',
        'Laba (rugi) per saham dilusian dari operasi yang dihentikan',
    ],
    "Arus Kas (Cash Flow)": [
        'Penerimaan dari pelanggan',
        'Penerimaan dari penjualan/penurunan modal atas investasi pada saham dan efek ekuitas lainnya',
        'Penerimaan subsidi',
        'Penerimaan dari royalti, fees, komisi, dan pendapatan lain',
        'Penerimaan dari kontrak yang dimiliki untuk tujuan diperdagangkan atau diperjualbelikan',
        'Penerimaan dari perusahaan efek',
        'Penerimaan kas lainnya dari aktivitas operasi',
        'Penerimaan bunga, hasil investasi, provisi, dan komisi',
        'Penerimaan dari penyertaan saham dalam klasifikasi biaya perolehan diamortisasi dan nilai wajar melalui pendapatan komprehensif lainnya',
        'Penerimaan dari penjualan atas investasi pada efek',
        'Penerimaan dividen dari aktivitas operasi',
        'Penerimaan bunga dari aktivitas operasi',
        'Penerimaan pengembalian (pembayaran) pajak penghasilan dari aktivitas operasi',
        'Pengembalian (penempatan) uang jaminan',
        'Penerimaan (pengeluaran) kas lainnya dari aktivitas operasi',
        'Pembayaran kepada pemasok atas barang dan jasa',
        'Pembayaran gaji dan tunjangan',
        'Pembayaran beban umum dan administrasi',
        'Pembayaran royalti dan iuran eksploitasi',
        'Pembayaran kepada kontraktor',
        'Pembayaran jasa manajemen',
        'Pembayaran kas lainnya untuk beban operasi',
        'Pembayaran dari kontrak yang dimiliki untuk tujuan diperdagangkan atau diperjualbelikan',
        'Pembayaran bunga dan bonus, provisi dan komisi',
        'Pembayaran utang cukai',
        'Pembayaran pajak penghasilan badan',
        'Pembayaran dividen dari aktivitas operasi',
        'Pembayaran bunga dari aktivitas operasi',
        'Penempatan investasi pada efek',
        'Bunga bank dan deposito berjangka',
        'Penerimaan pendapatan pengelolaan dana sebagai mudharib',
        'Pembayaran bagi hasil dana syirkah temporer',
        'Penerimaan premi asuransi',
        'Penerimaan klaim reasuransi',
        'Penerimaan (pembayaran) komisi',
        'Penerimaan klaim retrosesi',
        'Penerimaan dari ujrah',
        'Penerimaan dari (pembayaran kepada) lembaga kliring dan penjaminan',
        'Penerimaan dari (pembayaran kepada) nasabah',
        'Pencairan (penempatan) deposito pada lembaga kliring dan penjaminan',
        'Pendapatan dari transaksi operasional lainnya',
        'Penerimaan kembali aset yang telah dihapusbukukan',
        'Pembayaran biaya akuisisi ditangguhkan',
        'Pembayaran atas beban keuangan dan beban administrasi bank',
        'Laba (rugi) selisih kurs',
        'Pembayaran beban operasional lainnya',
        'Penerimaan pendapatan non-operasional',
        'Penurunan (kenaikan) efek-efek',
        'Penurunan (kenaikan) kredit',
        'Penurunan (kenaikan) aset lainnya',
        'Kenaikan (penurunan) simpanan dan simpanan dari bank lain',
        'Kenaikan (penurunan) liabilitas lainnya',
        'Penurunan (kenaikan) penempatan pada bank lain dan Bank Indonesia',
        'Penurunan (kenaikan) efek yang diperdagangkan',
        'Penurunan (kenaikan) efek yang dibeli dengan janji dijual kembali',
        'Penurunan (kenaikan) investasi pemegang polis pada kontrak unit-linked',
        'Penurunan (kenaikan) wesel ekspor dan tagihan lainnya',
        'Penurunan (kenaikan) tagihan akseptasi',
        'Penurunan (kenaikan) pinjaman yang diberikan',
        'Penurunan (kenaikan) piutang pembiayaan konsumen',
        'Penurunan (kenaikan) investasi sewa',
        'Penurunan (kenaikan) tagihan anjak piutang',
        'Penurunan (kenaikan) piutang murabahah',
        'Penurunan (kenaikan) piutang istishna',
        'Penurunan (kenaikan) piutang ijarah',
        'Penurunan (kenaikan) pinjaman qardh',
        'Penurunan (kenaikan) pembiayaan mudharabah',
        'Penurunan (kenaikan) pembiayaan musyarakah',
        'Penurunan (kenaikan) aset ijarah',
        'Penurunan (kenaikan) piutang lainnya',
        'Penurunan (kenaikan) agunan yang diambil alih',
        'Penurunan (kenaikan) tagihan derivatif',
        'Penurunan (kenaikan) aset reasuransi',
        'Kenaikan (penurunan) liabilitas segera',
        'Kenaikan (penurunan) giro dan tabungan simpanan nasabah',
        'Kenaikan (penurunan) deposito berjangka nasabah',
        'Kenaikan (penurunan) giro wadiah simpanan nasabah',
        'Kenaikan (penurunan) tabungan wadiah simpanan nasabah',
        'Kenaikan (penurunan) deposito wakalah simpanan nasabah',
        'Kenaikan (penurunan) simpanan dari bank lain',
        'Kenaikan (penurunan) giro mudharabah',
        'Kenaikan (penurunan) tabungan mudharabah',
        'Kenaikan (penurunan) efek yang dijual dengan janji dibeli kembali',
        'Kenaikan (penurunan) liabilitas akseptasi',
        'Kenaikan (penurunan) liabilitas pemegang polis pada kontrak unit-linked',
        'Kenaikan (penurunan) liabilitas derivatif',
        'Kenaikan (penurunan) dana syirkah temporer',
        'Pembayaran biaya pengupasan tanah ditangguhkan',
        'Pembayaran biaya mobilisasi ditangguhkan',
        'Pembayaran biaya ditangguhkan',
        'Penerimaan dari (pengeluaran untuk) dana pemeliharaan pesawat',
        'Pembayaran uang muka pembelian aset tetap',
        'Penerimaan dari penjualan persediaan hewan ternak produksi',
        'Pembayaran untuk perolehan persediaan hewan ternak produksi',
        'Penerimaan dari penjualan hutan tanaman industri',
        'Pembayaran untuk perolehan hutan tanaman industri',
        'Penerimaan dari penjualan tanaman perkebunan',
        'Pembayaran untuk perolehan tanaman perkebunan',
        'Penerimaan dari penjualan perkebunan plasma',
        'Pembayaran untuk perolehan perkebunan plasma',
        'Penerimaan dari penjualan properti investasi',
        'Pembayaran untuk perolehan properti investasi',
        'Penerimaan dari penjualan aset tetap',
        'Pembayaran untuk perolehan aset tetap',
        'Penerimaan dari penjualan aset agunan yang diambil alih',
        'Penerimaan dari penjualan aset minyak dan gas bumi',
        'Pembayaran untuk perolehan aset minyak dan gas bumi',
        'Penerimaan dari penjualan aset eksplorasi dan evaluasi',
        'Pembayaran untuk perolehan aset eksplorasi dan evaluasi',
        'Penerimaan dari penjualan hak penguasaan jalan tol',
        'Pembayaran untuk perolehan hak penguasaan jalan tol',
        'Penerimaan dari penjualan properti pertambangan',
        'Pembayaran untuk perolehan properti pertambangan',
        'Penerimaan dari penjualan aset takberwujud',
        'Pembayaran untuk perolehan aset takberwujud',
        'Penerimaan dari penjualan tanah dalam pengembangan',
        'Pembayaran untuk perolehan tanah dalam pengembangan',
        'Penerimaan dari penjualan aset non-keuangan lainnya',
        'Pembayaran untuk perolehan aset non-keuangan lainnya',
        'Pencairan (penempatan) investasi jangka pendek',
        'Pencairan (penempatan) aset keuangan yang diukur pada nilai wajar melalui laba rugi',
        'Pencairan (penempatan) aset keuangan nilai wajar melalui pendapatan komprehensif lainnya',
        'Pencairan (penempatan) dana yang dibatasi penggunaannya dari aktivitas investasi',
        'Pencairan (penempatan) obligasi dan (atau) sukuk',
        'Penempatan aset keuangan biaya perolehan diamortisasi',
        'Pencairan aset keuangan biaya perolehan diamortisasi',
        'Penerimaan dari penjualan aset keuangan',
        'Pembayaran untuk perolehan aset keuangan',
        'Penerimaan dari future contracts, forward contracts, option contracts, dan swap contracts',
        'Pembayaran untuk future contracts, forward contracts, option contracts, dan swap contracts',
        'Pembayaran uang muka investasi',
        'Penerimaan pembayaran piutang dari pihak berelasi',
        'Pembayaran pemberian piutang kepada pihak berelasi',
        'Penerimaan pembayaran piutang dari pemegang saham',
        'Pembayaran pemberian piutang kepada pemegang saham',
        'Uang muka dan pinjaman diberikan kepada pihak lain, selain institusi keuangan',
        'Penerimaan pengembalian uang muka dan pinjaman diberikan kepada pihak lain',
        'Penerimaan dari pelepasan entitas anak',
        'Pembayaran untuk perolehan entitas anak',
        'Penerimaan dari pelepasan kepentingan di entitas anak tanpa hilangnya pengendalian dari kegiatan investasi',
        'Pembayaran untuk perolehan tambahan kepemilikan pada entitas anak',
        'Penerimaan dari pelepasan kepemilikan pada entitas ventura bersama',
        'Pembayaran untuk perolehan kepemilikan pada entitas ventura bersama',
        'Penerimaan dari pelepasan kepemilikan pada entitas asosiasi',
        'Pembayaran untuk perolehan kepemilikan pada entitas asosiasi',
        'Penerimaan dari pelepasan aset tidak lancar atau kelompok lepasan yang diklasifikasikan sebagai dimiliki untuk dijual dan operasi yang dihentikan',
        'Penerimaan dividen dari aktivitas investasi',
        'Penerimaan bunga dari aktivitas investasi',
        'Pembayaran bunga dari aktivitas investasi',
        'Penerimaan pengembalian (pembayaran) pajak penghasilan dari aktivitas investasi',
        'Penerimaan (pengeluaran) kas lainnya dari aktivitas investasi',
        'Penerimaan dari (pembayaran kepada) pinjaman polis',
        'Pencairan (penempatan) efek-efek yang diperdagangkan',
        'Penerimaan pinjaman bank',
        'Pembayaran pinjaman bank',
        'Penerimaan pinjaman dari lembaga keuangan non-bank',
        'Pembayaran pinjaman kepada lembaga keuangan non-bank',
        'Penerimaan pinjaman beragunan',
        'Pembayaran pinjaman beragunan',
        'Penerimaan pinjaman tanpa agunan',
        'Pembayaran pinjaman tanpa agunan',
        'Penerimaan pinjaman penerusan',
        'Pembayaran pinjaman penerusan',
        'Penerimaan utang dari bantuan pemerintah republik Indonesia',
        'Pembayaran utang bantuan dari pemerintah republik Indonesia',
        'Penerimaan pinjaman subordinasi',
        'Pembayaran pinjaman subordinasi',
        'Penerimaan liabilitas kerjasama operasi',
        'Pembayaran liabilitas kerjasama operasi',
        'Penerimaan utang pembiayaan konsumen',
        'Pembayaran utang pembiayaan konsumen',
        'Penerimaan liabilitas sewa pembiayaan',
        'Pembayaran liabilitas sewa pembiayaan',
        'Penerimaan utang listrik swasta',
        'Pembayaran utang listrik swasta',
        'Penerimaan utang retensi',
        'Pembayaran utang retensi',
        'Penerimaan wesel bayar',
        'Pembayaran wesel bayar',
        'Penerimaan dari surat utang jangka menengah',
        'Pembayaran dari surat utang jangka menengah',
        'Penerimaan dari penerbitan obligasi',
        'Pembayaran utang obligasi',
        'Obligasi subordinasi yang diterbitkan',
        'Pembayaran obligasi subordinasi',
        'Penerimaan sukuk',
        'Pembayaran sukuk',
        'Penerimaan pinjaman lainnya',
        'Pembayaran pinjaman lainnya',
        'Penerimaan dari penerbitan obligasi konversi',
        'Pembayaran obligasi konversi',
        'Pembayaran biaya emisi penerbitan obligasi',
        'Pencairan (penempatan) dana yang dibatasi penggunaannya dari aktivitas pendanaan',
        'Penerimaan utang pihak berelasi',
        'Pembayaran utang pihak berelasi',
        'Penerimaan utang pemegang saham',
        'Pembayaran utang pemegang saham',
        'Penerimaan dari penerbitan saham biasa',
        'Penerimaan dari penerbitan saham preferen',
        'Penerimaan dari penerbitan instrumen ekuitas lainnya',
        'Pembayaran biaya emisi saham',
        'Penerimaan dari penjualan (pembelian) saham tresuri',
        'Penerimaan dari program opsi saham karyawan',
        'Penyelesaian (penempatan) transaksi derivatif',
        'Penerimaan dari pelepasan kepentingan di entitas anak tanpa hilangnya pengendalian dari kegiatan pendanaan',
        'Penerimaan dari penambahan kepemilikan dari non-pengendali',
        'Pembayaran untuk perolehan kepentingan pihak non-pengendali pada entitas anak',
        'Pembayaran dividen dari aktivitas pendanaan',
        'Penerimaan bunga dari aktivitas pendanaan',
        'Pembayaran bunga dari aktivitas pendanaan',
        'Penerimaan pengembalian (pembayaran) pajak penghasilan dari aktivitas pendanaan',
        'Penerimaan (pengeluaran) kas lainnya dari aktivitas pendanaan',
        'Kenaikan (penurunan) efek yang diterbitkan',
        'Penerbitan sukuk mudharabah',
        'Penempatan sertifikat investasi mudharabah',
        'Biaya emisi sukuk mudharabah',
        'Penerimaan pinjaman yang diterima',
        'Pembayaran pinjaman yang diterima',
        'Biaya emisi obligasi subordinasi yang diterbitkan',
        'Pembayaran bunga pinjaman',
        'Penerimaan setoran modal',
        'Jumlah kenaikan (penurunan) bersih kas dan setara kas',
        'Kas dan setara kas arus kas, awal periode',
        'Efek perubahan nilai kurs pada kas dan setara kas',
        'Kas dan setara kas dari entitas anak yang didekonsolidasikan',
        'Kenaikan (penurunan) kas dan setara kas lainnya',
        'Kas dan setara kas arus kas, akhir periode',
    ],
    "Agregat & Metrik Keuangan": [
        # Neraca — total/subtotal
        'Jumlah aset lancar',
        'Jumlah aset tidak lancar',
        'Jumlah aset',
        'Jumlah liabilitas jangka pendek',
        'Jumlah liabilitas jangka panjang',
        'Jumlah liabilitas',
        'Modal ditempatkan dan disetor penuh',
        'Jumlah ekuitas yang dapat diatribusikan kepada pemilik entitas induk',
        'Jumlah ekuitas',
        # Laba Rugi — total/subtotal
        'Jumlah laba bruto',
        'Jumlah laba (rugi) usaha',
        'Jumlah laba (rugi) sebelum pajak penghasilan',
        'Jumlah laba (rugi)',
        'Laba (rugi) per saham dasar',
        'Pendapatan operasional lainnya',
        # Arus Kas — total
        'Jumlah arus kas dari aktivitas operasi',
        'Jumlah arus kas dari aktivitas investasi',
        'Jumlah arus kas dari aktivitas pendanaan',
        'Kas dan setara kas akhir periode',
        # Beban non-kas (untuk EBITDA)
        'Depresiasi',
        'Amortisasi',
    ],
}

# Flat list semua akun (urutan: General → BS → IS → CF)
ALL_METRICS: list = []
for _cat_metrics in METRICS_CATALOG.values():
    ALL_METRICS.extend(_cat_metrics)

# Default: akun aktif saat install pertama
DEFAULT_METRICS = ['Nama entitas', 'Kode entitas', 'Sektor', 'Subsektor', 'Industri', 'Subindustri', 'Periode penyampaian laporan keuangan', 'Mata uang pelaporan', 'Pembulatan yang digunakan dalam penyajian jumlah dalam laporan keuangan', 'Jenis laporan atas laporan keuangan', 'Tanggal laporan audit atau hasil laporan review', 'Kas dan setara kas', 'Jumlah aset lancar', 'Jumlah aset tidak lancar', 'Jumlah aset', 'Jumlah liabilitas jangka pendek', 'Jumlah liabilitas jangka panjang', 'Jumlah liabilitas', 'Modal ditempatkan dan disetor penuh', 'Saldo laba yang belum ditentukan penggunaannya', 'Jumlah ekuitas yang dapat diatribusikan kepada pemilik entitas induk', 'Jumlah ekuitas', 'Penjualan dan pendapatan usaha', 'Beban pokok penjualan dan pendapatan', 'Jumlah laba bruto', 'Jumlah laba (rugi) usaha', 'Pendapatan bunga', 'Beban bunga dan keuangan', 'Beban bunga', 'Jumlah laba (rugi) sebelum pajak penghasilan', 'Jumlah laba (rugi)', 'Laba (rugi) yang dapat diatribusikan ke entitas induk', 'Laba (rugi) per saham dasar', 'Jumlah arus kas dari aktivitas operasi', 'Jumlah arus kas dari aktivitas investasi', 'Jumlah arus kas dari aktivitas pendanaan', 'Kas dan setara kas akhir periode', 'Depresiasi', 'Amortisasi']

# ── Preset: Altman Z-Score — akun yang dibutuhkan untuk kalkulasi ──────────
ALTMAN_ACCOUNTS = [
    'Nama entitas',
    'Kode entitas',
    'Sektor',
    'Subsektor',
    'Industri',
    'Subindustri',
    'Periode penyampaian laporan keuangan',
    'Mata uang pelaporan',
    'Pembulatan yang digunakan dalam penyajian jumlah dalam laporan keuangan',
    'Jumlah aset',
    'Jumlah aset lancar',
    'Jumlah liabilitas jangka pendek',
    'Jumlah ekuitas',
    'Saldo laba yang belum ditentukan penggunaannya',
    'Saldo laba yang telah ditentukan penggunaannya',
    'Penjualan dan pendapatan usaha',
    'Jumlah laba (rugi) sebelum pajak penghasilan',
    'Beban bunga dan keuangan',
    'Jumlah liabilitas',
    'Depresiasi',
    'Amortisasi',
    'Beban bunga',
    'Pendapatan bunga',
    'Pendapatan operasional lainnya',
]

# ── Preset: Interest Bearing Debt (IBD) — semua komponen utang berbunga ───
IBD_ACCOUNTS = [
    'Nama entitas',
    'Kode entitas',
    'Sektor',
    'Subsektor',
    'Industri',
    'Subindustri',
    'Periode penyampaian laporan keuangan',
    'Mata uang pelaporan',
    'Pembulatan yang digunakan dalam penyajian jumlah dalam laporan keuangan',
    'Utang bank jangka pendek',
    'Utang trust receipts',
    'Pinjaman jangka pendek non-bank',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang bank',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang keuangan keuangan non bank',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang obligasi',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas surat utang jangka menengah',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas utang pembiayaan konsumen',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas liabilitas sewa pembiayaan',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas sukuk',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas obligasi subordinasi',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman beragunan',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman tanpa agunan',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas penerusan pinjaman',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman dari pemerintah republik Indonesia',
    'Liabilitas jangka panjang yang jatuh tempo dalam satu tahun atas pinjaman subordinasi',
    'Liabilitas jangka panjang atas utang bank',
    'Liabilitas jangka panjang atas utang obligasi',
    'Utang lembaga keuangan non-bank',
    'Liabilitas jangka panjang atas pinjaman beragunan',
    'Liabilitas jangka panjang atas pinjaman tanpa agunan',
    'Liabilitas jangka panjang atas pinjaman dari pemerintah republik Indonesia',
    'Liabilitas jangka panjang atas pinjaman subordinasi',
    'Liabilitas jangka panjang atas utang pembiayaan konsumen',
    'Liabilitas jangka panjang atas surat utang jangka menengah',
    'Liabilitas jangka panjang atas sukuk',
    'Liabilitas jangka panjang atas obligasi subordinasi',
    'Liabilitas jangka panjang atas liabilitas sewa pembiayaan',
]

TARGET_CONTEXTS = ["CurrentYearInstant", "CurrentYearDuration"]


def _clean_value(value_text):
    if not value_text:
        return None
    value_text = value_text.strip()
    if not value_text or value_text.lower() in ["", "nan", "none"]:
        return None
    is_negative = False
    if value_text.startswith("(") and value_text.endswith(")"):
        is_negative = True
        value_text = value_text[1:-1]
    try:
        clean_text = value_text.replace(",", "")
        result = float(clean_text) if "." in clean_text else int(clean_text)
        if is_negative:
            result = -result
        return result
    except ValueError:
        return value_text


def _extract_from_dir(company_dir: Path, metrics: list) -> dict:
    company_name = company_dir.name.split("_")[0]
    metrics_found = {}
    html_files = list(company_dir.glob("*.html"))
    if not html_files:
        return {"company": company_name, "folder": company_dir.name, "metrics": {}}

    metrics_set = set(metrics)

    for html_file in html_files:
        if not metrics_set - set(metrics_found.keys()):
            break  # semua metrik sudah ditemukan
        try:
            with open(html_file, "r", encoding="utf-8") as f:
                content = f.read()
            soup = BeautifulSoup(content, "html.parser")
            rows = soup.find_all("tr")
            for row in rows:
                header_cell = row.find("td", class_="rowHeaderLeft")
                if not header_cell:
                    continue
                header_text = header_cell.get_text(strip=True)
                if header_text not in metrics_set or header_text in metrics_found:
                    continue
                value_cells = row.find_all("td", class_="valueCell")
                for value_cell in value_cells:
                    ix_elems = value_cell.find_all(["ix:nonfraction", "ix:nonnumeric"])
                    for ix_elem in ix_elems:
                        if ix_elem.get("contextref", "") not in TARGET_CONTEXTS:
                            continue
                        if ix_elem.get("xsi:nil") == "true":
                            continue
                        value = ix_elem.get_text(strip=True)
                        sign_attr = ix_elem.get("sign", "")
                        cell_text = value_cell.get_text(strip=True)
                        has_parens = cell_text.startswith("(") and cell_text.endswith(")")
                        cleaned = _clean_value(value)
                        if cleaned is not None and isinstance(cleaned, (int, float)):
                            if header_text in ("Beban bunga dan keuangan", "Beban bunga"):
                                # Beban selalu positif — paksa abs() apapun tanda aslinya
                                cleaned = abs(cleaned)
                            elif has_parens or sign_attr == "-":
                                cleaned = -abs(cleaned)
                        if cleaned is not None:
                            metrics_found[header_text] = {"value": cleaned, "file": html_file.name}
                            break
                    if header_text in metrics_found:
                        break
        except Exception:
            continue

    return {"company": company_name, "folder": company_dir.name, "metrics": metrics_found}


def extract_all(xbrl_dir: str, output_dir: str,
                selected_metrics: list = None,
                progress_callback=None, log_callback=None,
                stop_flag=None) -> str:
    """
    Ekstrak data XBRL dari semua folder perusahaan.

    Args:
        selected_metrics: List nama akun yang akan diekstrak.
                          Jika None, gunakan DEFAULT_METRICS.
    Returns:
        Path ke summary CSV, atau None jika gagal.
    """
    def log(msg):
        if log_callback: log_callback(msg)
        else: print(msg)

    metrics = selected_metrics if selected_metrics else DEFAULT_METRICS
    log(f"Mengekstrak {len(metrics)} akun yang dipilih...")

    src = Path(xbrl_dir)
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    company_dirs = [d for d in src.iterdir() if d.is_dir()]
    if not company_dirs:
        log(f"Tidak ada folder perusahaan di: {xbrl_dir}")
        return None

    total = len(company_dirs)
    log(f"Ditemukan {total} perusahaan.\n")
    all_results = []

    for i, company_dir in enumerate(company_dirs, 1):
        if stop_flag and stop_flag():
            log("Dihentikan oleh user.")
            break
        log(f"[{i}/{total}] {company_dir.name}")
        result = _extract_from_dir(company_dir, metrics)
        all_results.append(result)
        found = len(result["metrics"])
        log(f"  → {found}/{len(metrics)} akun ditemukan")
        if progress_callback:
            progress_callback(i, total)

    # Build summary
    summary_data = []
    for result in all_results:
        row = {"Company": result["company"], "Folder": result["folder"]}
        for metric in metrics:
            row[metric] = result["metrics"].get(metric, {}).get("value", None)
        summary_data.append(row)

    df = pd.DataFrame(summary_data)
    out_file = out / "00_SUMMARY_all_companies.csv"
    df.to_csv(out_file, index=False, encoding="utf-8-sig")
    log(f"\n✓ Summary → {out_file}")
    log(f"✓ {len(all_results)} perusahaan, {len(metrics)} akun")
    return str(out_file)
